# Generated by Django 2.2 on 2020-11-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190829_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasosEnviados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('Cantidad', models.CharField(default='', max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
