# Generated by Django 2.2 on 2020-11-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201126_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallCenters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_call', models.CharField(default='', max_length=20)),
                ('Description', models.CharField(default='', max_length=50)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_comuna', models.CharField(default='', max_length=20)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_estado', models.CharField(default='', max_length=20)),
                ('Activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CasosRecibiados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='', max_length=20)),
                ('date', models.DateField()),
                ('Cantidad', models.CharField(default='', max_length=30)),
                ('callcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.CallCenters')),
            ],
        ),
        migrations.CreateModel(
            name='CasosEstado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Cantidad', models.CharField(default='', max_length=30)),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Estados')),
            ],
        ),
        migrations.CreateModel(
            name='CasosComunas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Cantidad', models.CharField(default='', max_length=30)),
                ('Comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Comunas')),
            ],
        ),
    ]
